version: "3.8"

services:
  configserver:
    image: arancibia/bodega-config-server
    restart: always
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
      - eazybank-network
  bodega_db:
    image: mysql
    restart: always
    volumes:
      - /Users/aarancis/IdeaProjects/utp/bodega-app-ms/bodega-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
  bodega_adminer:
    image: adminer
    restart: always
    ports:
      - "8088:8080"
  bodegastore:
    image: arancibia/bodegastore
    mem_limit: 700m
    restart: always
    ports:
      - "8020:8020"
    networks:
      - eazybank-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_APPLICATION_NAME: bodega
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

networks:
  eazybank-network: