server.port=8020
server.servlet.context-path=/api
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=none

spring.sql.init.mode=${SPRING_SQL_INIT_MODE:never}

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI:https://euc1.auth.ac/auth/realms/portfoliodev/protocol/openid-connect/certs}
spring.datasource.url=${SPRING_DATA_SOURCE_URL:jdbc:postgresql://localhost:5433/carrito}
spring.datasource.username=${SPRING_DATA_SOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATA_SOURCE_PASSWORD:1234}
paypay.api.key=${PAYPAY_API_KEY:a_qNZeEkUM6W_oVil}
paypay.api.secretKey=${PAYPAY_API_SECRET_KEY:HtLFDgMS9T2MgYtCcNXgIJ17HnqB3JyPTRCr4hRjDUg=}
paypay.api.merchantId=${PAYPAY_API_SECRET_MERCHANT_ID:871905054989828096}
paypal.urlV1=${PAYPAY_API_URL_V1:https://api-m.sandbox.paypal.com/v1}
paypal.urlV2=${PAYPAY_API_URL_V2:https://api-m.sandbox.paypal.com/v2}
paypal.clientId=${PAYPAY_API_CLIENT_ID:AYezhSG1lTyPxcZy2qjIf9Xvg4f8jyeFFdLpmGTyqeCxar7uyjH7LmwJKnIcYbwlJYnk6cvcu4rD9ZF3}
paypal.secret=${PAYPAY_API_SECRET:EG9S3bS-zmUJFy33iTXucZdVdOOesZNAGZG1BswlxV14qKrWogDgTxSj_lhhcu7ew5pivqxafDdryboT}
keycloak.baseUrl=${KEYCLOAK_BASE_URL:https://euc1.auth.ac/auth}
keycloak.realm=${KEYCLOAK_REALM:portfoliodev}

spring.flyway.enabled=${SPRING_FLYWAY_ENABLED:true}
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migrations
spring.flyway.validate-on-migrate=true